# Generated by Django 3.2 on 2022-02-28 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=80)),
                ('venue_link', models.CharField(max_length=100, unique=True)),
                ('additional_info', models.TextField(blank=True)),
                ('contact_info', models.CharField(max_length=50)),
                ('emergency_info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Proposal'), (1, 'Approved')], default=0)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_event', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_venue', to='agenda.venue')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
