# Generated by Django 3.2 on 2022-02-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='event_name',
            field=models.CharField(default='party-', max_length=50, unique=True),
        ),
    ]
