# Generated by Django 3.2 on 2022-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20220307_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='play_time',
            field=models.CharField(default='E.g.: 2 hours', max_length=50),
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default='city name', max_length=100),
        ),
    ]
