# Generated by Django 3.2 on 2022-03-13 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20220308_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 13, 17, 42, 10, 558467)),
        ),
        migrations.AlterField(
            model_name='gig',
            name='event_date',
            field=models.DateField(),
        ),
    ]
