# Generated by Django 3.2 on 2022-03-13 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20220313_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 13, 17, 43, 46, 144976, tzinfo=utc)),
        ),
    ]
