# Generated by Django 3.2 on 2022-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_gig_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.CharField(default='0:00', max_length=20),
        ),
    ]
